spring:
  jpa:
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false
  datasource:
    url: jdbc:mysql://accounting-db:3306/accounting?useUnicode=true&characterEncoding=utf8
    username: accounting
    password: accounting
    driver-class-name: com.mysql.jdbc.Driver
  liquibase:
    enabled: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 3MB
      max-request-size: 10MB
  cache:
    type: jcache
    jcache:
      provider: org.ehcache.jsr107.EhcacheCachingProvider
    cache-names: acl_cache
  security:
    oauth2:
      client:
        registration:
          gigachat:
            # client-id: <set client id via environment variable>
            # client-secret: <set client secret via environment variable>
            authorization-grant-type: client_credentials
            scope: GIGACHAT_API_PERS
        provider:
          gigachat:
            token-uri: https://ngw.devices.sberbank.ru:9443/api/v2/oauth

server:
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      force-response: true

nalogru:
  address: https://proverkacheka.nalog.ru:9999

nalogru2:
  address: https://irkkt-mobile.nalog.ru:8888

cashreceipts:
  liquibase:
    enabled: true
    change-log: classpath:db/cashreceipt/changelog/db.changelog-master.xml

accounting:
  ai:
    gigachat:
      model: GigaChat-Pro
    purchases:
      collection: AccountingPurchases
      index:
        initial-delay: 3000
        delay: 3600000
    milvus:
      host: 10.5.5.80
      port: 32530
  liquibase:
    enabled: true
    change-log: classpath:db/accounting/changelog/db.changelog-master.xml

application:
  version: ^project.version^
  liquibase:
    enabled: true
    change-log: classpath:db/application/changelog/db.changelog-master.xml


alfabank:
  reports:
    path: "/alfabank_reports"

tinkoff:
  reports:
    path: "/tinkoff_reports"

gazprombank:
  reports:
    path: "/gpb_reports"
    skip:
      - "3852360"
      - "1234567"

jwt:
  secret:
    access: NjI5ZmFiOGIzODM1YzNjOGQzY2M1Nzg2YTQ1MDIwNDY3ZDQzZTM5ODA1ZjBlZWQ0MmExYWE1YzBkMWZlNWM2Yg==
    refresh: M2Y2OTkzZTQ1NjE5MzcwZGIzNThhMThkY2UyNTY4MzIwM2VjZGY0MDk0N2EzMTI1NWU4NjQwYWM5ZGNhYTAwZQ==

debug: false

logging:
  level:
    ru.vzotov.cashreceipt: DEBUG
    ru.vzotov.accounting: DEBUG
